feat: Setup NTP
ChainSafe/forest-iac pull request #220
Opened 2023-08-17 14:13 UTC by samuelarogbonlo

**Summary of changes**
Changes introduced in this pull request:
- Install and Enable NTP to synchronize the time differences

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

2023-08-17 19:53 UTC, aatifsyed approved these changes

2023-08-17 20:32 UTC, LesnyRumcajs requested changes
I don't quite understand. You reverted NTP changes in https://github.com/ChainSafe/forest-iac/pull/146. Could you please provide context for both reverting and bringing it back again?

2023-08-17 20:34 UTC, LesnyRumcajs commented
Additionally, this branch contains changes from https://github.com/ChainSafe/forest-iac/pull/219, which should not be the case.

2023-08-18 08:13 UTC, LesnyRumcajs commented on .github/workflows/deploy-sync-check.yml
> +
```suggestion
```

2023-08-18 08:13 UTC, LesnyRumcajs commented on terraform/modules/filecoin_node/firewall.tf
> +  outbound_rule {
Let's add a comment on why it's needed.

2023-08-18 15:57 UTC, merged