feat: Precommit check for secrets leak and file linting
ChainSafe/forest-iac pull request #233
Opened 2023-08-29 11:57 UTC by samuelarogbonlo

**Summary of changes**
Changes introduced in this pull request:
- Pre-commit check for secrets leak and File linting
- added the docs for this feature. 

**Reference issue to close (if applicable)**

Closes #88 

**Other information and links**

2023-08-31 10:46 UTC, LesnyRumcajs requested changes
Let's add the docs for this feature in this PR. I can't really review it without the bigger picture and usage.

2023-09-01 11:28 UTC, LesnyRumcajs reviewed
Dismissing my review so it's not blocked for the duration of my PTO.

2023-09-04 08:12 UTC, lemmih requested changes
The formatting changes make it difficult for me to see the genuine modifications. Mind moving the formatting to a different PR?

2023-09-04 10:01 UTC, lemmih requested changes

2023-09-04 10:01 UTC, lemmih commented on README.md
> +    pre-commit install
Is `pre-commit` something everyone has installed?

2023-09-05 09:08 UTC, lemmih approved these changes

2023-09-05 09:48 UTC, merged