fix: increase remote exec timeout
ChainSafe/forest-iac pull request #439
Opened 2024-05-03 12:25 UTC by samuelarogbonlo

**Summary of changes**
Changes introduced in this pull request:
- increase remote exec timeout

**Reference issue to close (if applicable)**

Closes

**Other information and links**

2024-05-03 12:48 UTC, hanabi1224 approved these changes

2024-05-06 07:18 UTC, LesnyRumcajs requested changes
It's not only the daily snapshot that fails on timeouts; other services should be modified as well.

2024-05-06 10:03 UTC, samuelarogbonlo commented
> It's not only the daily snapshot that fails on timeouts; other services should be modified as well.

done.

2024-05-07 10:53 UTC, LesnyRumcajs commented
What about `forest-droplet`?

2024-05-08 13:10 UTC, lemmih approved these changes

2024-05-08 13:26 UTC, merged